export const DEVELOPER_ONBOARDING_STORAGE_KEY = "devonboarding";
export const PROJECT_PREFORM_STORAGE_KEY = "PROJECT_PREFORM_STORAGE_KEY";
export const PROJECT_SUBMISSION_STORAGE_KEY = "PROJECT_SUBMISSION_STORAGE_KEY";
